#include <iostream>
using namespace std;
class student
{
private:
public:
    string name;
    int marks;
    string section;

    student(); // this is a non parameterized constructor which is a constructor that does not take any arguments. It is called a default constructor because it is automatically generated by the compiler if no other constructors are defined in the class. In this case, we have explicitly defined a default constructor that simply prints a message to the console when an object of the class is created.

    student(string n, int m, string s); // this is a parameterized constructor which is a constructor that takes arguments. It allows you to initialize the data members of the class with specific values when an object is created. In this case, we have defined a parameterized constructor that takes three arguments (name, marks, and section) and initializes the corresponding data members of the class with those values.
    ~student();
};

student::student()
{

    cout << "This is use of a constructor" << endl;
}; // this is a simple constructor which is a special member function that is automatically called when an object of the class is created. It has the same name as the class and does not have a return type. The primary purpose of a constructor is to initialize the data members of the class. In this case, the constructor does not take any arguments and does not perform any initialization, but it can be used to set default values for the data members or to perform any other setup tasks that are necessary when an object is created.

student::student(string n, int m, string s)
{
    name = n;
    marks = m;
    section = s;
};

student::~student()
{
    cout << "This is use of a destructor" << endl;
}; // this is a destructor which is a special member function that is automatically called when an object of the class is destroyed. It has the same name as the class, preceded by a tilde (~), and does not have a return type. The primary purpose of a destructor is to perform any cleanup tasks that are necessary when an object is destroyed, such as releasing memory or closing files. In this case, the destructor does not perform any specific cleanup tasks, but it can be used to ensure that any resources allocated by the class are properly released when an object is destroyed.

int main()
{
    student s1;
    student s2("Aditya", 95, "A");
    cout << "Name: " << s2.name << ", Marks: " << s2.marks << ", Section: " << s2.section << endl;

    return 0;
}